DROP TABLE IF EXISTS nationalities;
CREATE TABLE IF NOT EXISTS nationalities(
   Nationality VARCHAR(29) NOT NULL PRIMARY KEY
  ,Country     VARCHAR(14)
);
INSERT INTO nationalities(Nationality,Country) VALUES ('Achaemenid','Iraq');
INSERT INTO nationalities(Nationality,Country) VALUES ('African','Africa');
INSERT INTO nationalities(Nationality,Country) VALUES ('Albanian','Albania');
INSERT INTO nationalities(Nationality,Country) VALUES ('Algerian','Algeria');
INSERT INTO nationalities(Nationality,Country) VALUES ('American','United States');
INSERT INTO nationalities(Nationality,Country) VALUES ('Ancient Roman','Italian');
INSERT INTO nationalities(Nationality,Country) VALUES ('Argentine','Argentina');
INSERT INTO nationalities(Nationality,Country) VALUES ('Asante','Ashani');
INSERT INTO nationalities(Nationality,Country) VALUES ('Asian','North Korea');
INSERT INTO nationalities(Nationality,Country) VALUES ('Australian','Australia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Austrian','Austria');
INSERT INTO nationalities(Nationality,Country) VALUES ('Bamana','Mali');
INSERT INTO nationalities(Nationality,Country) VALUES ('Bamileke','Cameroon');
INSERT INTO nationalities(Nationality,Country) VALUES ('Baul�','France');
INSERT INTO nationalities(Nationality,Country) VALUES ('Belgian','Belgium');
INSERT INTO nationalities(Nationality,Country) VALUES ('Beninese','Benin');
INSERT INTO nationalities(Nationality,Country) VALUES ('Bohemian','Bohemia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Brazilian','Brazil');
INSERT INTO nationalities(Nationality,Country) VALUES ('British','Briton');
INSERT INTO nationalities(Nationality,Country) VALUES ('Burkinabe','Burkina Faso');
INSERT INTO nationalities(Nationality,Country) VALUES ('Cameroonian','Cameroon');
INSERT INTO nationalities(Nationality,Country) VALUES ('Canadian','Canada');
INSERT INTO nationalities(Nationality,Country) VALUES ('Central African','Africa');
INSERT INTO nationalities(Nationality,Country) VALUES ('Chilean','Chile');
INSERT INTO nationalities(Nationality,Country) VALUES ('Chinese','China');
INSERT INTO nationalities(Nationality,Country) VALUES ('Chola','South America');
INSERT INTO nationalities(Nationality,Country) VALUES ('Colombian','Colombia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Congolese','Congo');
INSERT INTO nationalities(Nationality,Country) VALUES ('Congolese (Republic of Congo)','Congo');
INSERT INTO nationalities(Nationality,Country) VALUES ('Coptic Egyptian','Egypt');
INSERT INTO nationalities(Nationality,Country) VALUES ('Croatian','Croatia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Cuban','Cuba');
INSERT INTO nationalities(Nationality,Country) VALUES ('Cycladic','Greece');
INSERT INTO nationalities(Nationality,Country) VALUES ('Cypriot','Cyprus');
INSERT INTO nationalities(Nationality,Country) VALUES ('Czech','Chech Republic');
INSERT INTO nationalities(Nationality,Country) VALUES ('Czechoslovakian','Czechoslovakia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Danish','Dane');
INSERT INTO nationalities(Nationality,Country) VALUES ('Dogon','Mali');
INSERT INTO nationalities(Nationality,Country) VALUES ('Dutch','Germany');
INSERT INTO nationalities(Nationality,Country) VALUES ('Eastern European','Europe');
INSERT INTO nationalities(Nationality,Country) VALUES ('Ecuadorian','Ecuador');
INSERT INTO nationalities(Nationality,Country) VALUES ('Egyptian','Egypt');
INSERT INTO nationalities(Nationality,Country) VALUES ('Ejagham','Nigeria');
INSERT INTO nationalities(Nationality,Country) VALUES ('English','England');
INSERT INTO nationalities(Nationality,Country) VALUES ('Estonian','Estonia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Etruscan','Tuscany');
INSERT INTO nationalities(Nationality,Country) VALUES ('European','Europe');
INSERT INTO nationalities(Nationality,Country) VALUES ('Filipino','Phillippines');
INSERT INTO nationalities(Nationality,Country) VALUES ('Finnish','Finland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Flemish','Dutch');
INSERT INTO nationalities(Nationality,Country) VALUES ('French','France');
INSERT INTO nationalities(Nationality,Country) VALUES ('Georgian','Georgia');
INSERT INTO nationalities(Nationality,Country) VALUES ('German','Germany');
INSERT INTO nationalities(Nationality,Country) VALUES ('Greco-Bactrian','Afghanistan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Greek','Greece');
INSERT INTO nationalities(Nationality,Country) VALUES ('Greenlandic','Greenland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Guinean','Guinea');
INSERT INTO nationalities(Nationality,Country) VALUES ('Hungarian','Hungry');
INSERT INTO nationalities(Nationality,Country) VALUES ('Icelandic','Iceland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Indian','India');
INSERT INTO nationalities(Nationality,Country) VALUES ('Indo-Persian','Indonesia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Iranian','Iran');
INSERT INTO nationalities(Nationality,Country) VALUES ('Irish','Ireland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Israeli','Israel');
INSERT INTO nationalities(Nationality,Country) VALUES ('Italian','Italy');
INSERT INTO nationalities(Nationality,Country) VALUES ('Ivorian','France');
INSERT INTO nationalities(Nationality,Country) VALUES ('Japanese','Japan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Javanese','Japan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Jordanian','Jordan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Khmer','Cambodia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Kissi','Guinea');
INSERT INTO nationalities(Nationality,Country) VALUES ('Korean','Korea');
INSERT INTO nationalities(Nationality,Country) VALUES ('Kuba (Congolese)','Congo');
INSERT INTO nationalities(Nationality,Country) VALUES ('Liberian','Libya');
INSERT INTO nationalities(Nationality,Country) VALUES ('Lithuanian','Lithuania');
INSERT INTO nationalities(Nationality,Country) VALUES ('Luxembourgeois','Luxembourg');
INSERT INTO nationalities(Nationality,Country) VALUES ('Malagasy','Madagascar');
INSERT INTO nationalities(Nationality,Country) VALUES ('Malian','Mali');
INSERT INTO nationalities(Nationality,Country) VALUES ('Mesopotamian','Iraq');
INSERT INTO nationalities(Nationality,Country) VALUES ('Mexican','Mexico');
INSERT INTO nationalities(Nationality,Country) VALUES ('Montenegrin','Montenegro');
INSERT INTO nationalities(Nationality,Country) VALUES ('Moroccan','Morocco');
INSERT INTO nationalities(Nationality,Country) VALUES ('Mozambican','Mozambique');
INSERT INTO nationalities(Nationality,Country) VALUES ('Native American','United States');
INSERT INTO nationalities(Nationality,Country) VALUES ('Near Eastern','Egypt');
INSERT INTO nationalities(Nationality,Country) VALUES ('Nepalese','Nepal');
INSERT INTO nationalities(Nationality,Country) VALUES ('Netherlandish','Netherland');
INSERT INTO nationalities(Nationality,Country) VALUES ('New Zealander','New Zealand');
INSERT INTO nationalities(Nationality,Country) VALUES ('Nigerian','Nigeria');
INSERT INTO nationalities(Nationality,Country) VALUES ('Northern European','Europe');
INSERT INTO nationalities(Nationality,Country) VALUES ('Norwegian','Norway');
INSERT INTO nationalities(Nationality,Country) VALUES ('Pakistani','Pakistan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Panamanian','Panama');
INSERT INTO nationalities(Nationality,Country) VALUES ('Pende','Congo');
INSERT INTO nationalities(Nationality,Country) VALUES ('Persian','Persia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Peruvian','Peru');
INSERT INTO nationalities(Nationality,Country) VALUES ('Polish','Poland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Portuguese','Portugal');
INSERT INTO nationalities(Nationality,Country) VALUES ('Puerto Rican','Puerto rico');
INSERT INTO nationalities(Nationality,Country) VALUES ('Romanian','Romania');
INSERT INTO nationalities(Nationality,Country) VALUES ('Romano-Egyptian','Egpyt');
INSERT INTO nationalities(Nationality,Country) VALUES ('Russian','Russia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Scandinavian','Denmark');
INSERT INTO nationalities(Nationality,Country) VALUES ('Scottish','Scottland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Serbian','Slovakia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Sicilian','Italy');
INSERT INTO nationalities(Nationality,Country) VALUES ('Sierra Leonean','Sierra Leone');
INSERT INTO nationalities(Nationality,Country) VALUES ('Slovene','Slovenia');
INSERT INTO nationalities(Nationality,Country) VALUES ('South African','Egpyt');
INSERT INTO nationalities(Nationality,Country) VALUES ('South American','Bolivia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Spanish','Ecuador');
INSERT INTO nationalities(Nationality,Country) VALUES ('Sudanese','Sudan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Sumerian','Iraq');
INSERT INTO nationalities(Nationality,Country) VALUES ('Swabian','Germany');
INSERT INTO nationalities(Nationality,Country) VALUES ('Swedish','Swedan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Swiss','Switzerland');
INSERT INTO nationalities(Nationality,Country) VALUES ('Syrian','Sryia');
INSERT INTO nationalities(Nationality,Country) VALUES ('Syro-Hittite','Turkey');
INSERT INTO nationalities(Nationality,Country) VALUES ('Taiwanese','Taiwan');
INSERT INTO nationalities(Nationality,Country) VALUES ('Thai','Thailand');
INSERT INTO nationalities(Nationality,Country) VALUES ('Tibetan','Tibet');
INSERT INTO nationalities(Nationality,Country) VALUES ('Turkish','Turkey');
INSERT INTO nationalities(Nationality,Country) VALUES ('Turkish, Asia Minor','Turkey');
INSERT INTO nationalities(Nationality,Country) VALUES ('Turkish, Brusa','Turkey');
INSERT INTO nationalities(Nationality,Country) VALUES ('Ukrainian','Ukrane');
INSERT INTO nationalities(Nationality,Country) VALUES ('undetermined',NULL);
INSERT INTO nationalities(Nationality,Country) VALUES ('Uruguayan','Uruguay');
INSERT INTO nationalities(Nationality,Country) VALUES ('Venetian','Italy');
INSERT INTO nationalities(Nationality,Country) VALUES ('Venezuelan','Venezuela');
INSERT INTO nationalities(Nationality,Country) VALUES ('Vietnamese','Vietnam');
INSERT INTO nationalities(Nationality,Country) VALUES ('Yoruba','Nigeria');
INSERT INTO nationalities(Nationality,Country) VALUES ('Yugoslavian','Yugoslavia');
